// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUEm0bNCsWb6BQQYUW1voIiJ1Su0qPjEw',
    appId: '1:87968147770:web:c9feb411b6d0c556804803',
    messagingSenderId: '87968147770',
    projectId: 'movies-app-8c0af',
    authDomain: 'movies-app-8c0af.firebaseapp.com',
    storageBucket: 'movies-app-8c0af.firebasestorage.app',
    measurementId: 'G-PGDJZ1D6GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8yZkelmiWjj4UyFUTeKqXmNbwZErf438',
    appId: '1:87968147770:android:c8a2dc6859af8925804803',
    messagingSenderId: '87968147770',
    projectId: 'movies-app-8c0af',
    storageBucket: 'movies-app-8c0af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFcfUAC9hwZkxulaYYGFhr-xdZrlxag0',
    appId: '1:87968147770:ios:0a3f7c3c1e2a47d7804803',
    messagingSenderId: '87968147770',
    projectId: 'movies-app-8c0af',
    storageBucket: 'movies-app-8c0af.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdFcfUAC9hwZkxulaYYGFhr-xdZrlxag0',
    appId: '1:87968147770:ios:0a3f7c3c1e2a47d7804803',
    messagingSenderId: '87968147770',
    projectId: 'movies-app-8c0af',
    storageBucket: 'movies-app-8c0af.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUEm0bNCsWb6BQQYUW1voIiJ1Su0qPjEw',
    appId: '1:87968147770:web:1fb978c7560554c7804803',
    messagingSenderId: '87968147770',
    projectId: 'movies-app-8c0af',
    authDomain: 'movies-app-8c0af.firebaseapp.com',
    storageBucket: 'movies-app-8c0af.firebasestorage.app',
    measurementId: 'G-1NL5KR58GW',
  );
}
